### ISSUE TITLE
Test creation

### ISSUE THREAD

**Issue by FranckSilvestre** [elaastic/elaastic-mytests#48]
### Description

As a student 
I want create a test 
So that I'll be able to play a test

### Tasks

- [x] relationnal data  schema study
- [x] ORM Mapping on existing entities
- [x] Class diagram design
- [x] Creation of new entities (StudentTest, etc.) 
- [ ] Services identification and specification 
- [ ] Services implantation
- [ ] API REST for services (see swagger)
- [ ] Service layer on the front office (Angular)
- [ ] Binding front with back office
